image: node:16
pipelines:
  branches:
    master:
      - step:
          name: Install Dependencies
          caches:
            - node
          script:
            - npm install
            - npm install @nestjs/cli
      - step:
          name: Build and Test
          script:
            - npm run build
            - npm test